# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: swaps-prices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swaps-prices
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: swaps-prices
    spec:
      containers:
      - name: swaps-prices
        image: IMAGE_NAME
        ports:
        - containerPort: 3030
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: swaps-prices-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3030
  selector:
    app: swaps-prices
